duckpan-update: Fix indentation

diff --git a/cookbooks/duckduckhack-vm/files/default/etc/init.d/duckpan-update b/cookbooks/duckduckhack-vm/files/default/etc/init.d/duckpan-update
--- a/cookbooks/duckduckhack-vm/files/default/etc/init.d/duckpan-update
+++ b/cookbooks/duckduckhack-vm/files/default/etc/init.d/duckpan-update
@@ -19,24 +19,27 @@ LOG_PATH=/var/log/boot.log
 # Often during DuckDuckHack VM development, you commented out the lines in the
 # DuckPAN cookbook in order to speed up your testing of the VM. If so, this
 # script should exit cleanly.
-function exit_not_installed(){
-echo "DuckPAN is not installed or the installation path is no longer"
-echo "${INSTALL_PATH}"
-echo "Exiting duckpan-update"
-initctl emit --no-wait duckpan-updated
-exit 0
+function exit_not_installed()
+{
+	echo "DuckPAN is not installed or the installation path is no longer"
+	echo "${INSTALL_PATH}"
+	echo "Exiting duckpan-update"
+	initctl emit --no-wait duckpan-updated
+	exit 0
 }
-function exit_failed_to_download(){
-echo "Failed to download"
-echo "Exiting duckpan-update"
-initctl emit --no-wait duckpan-updated
-exit 0
+function exit_failed_to_download()
+{
+	echo "Failed to download"
+	echo "Exiting duckpan-update"
+	initctl emit --no-wait duckpan-updated
+	exit 0
 }
-function exit_failed_to_run(){
-echo "Failed to run update script"
-echo "Exiting duckpan-update"
-initctl emit --no-wait duckpan-updated
-exit 0
+function exit_failed_to_run()
+{
+	echo "Failed to run update script"
+	echo "Exiting duckpan-update"
+	initctl emit --no-wait duckpan-updated
+	exit 0
 }
 
 
@@ -46,7 +49,7 @@ case "$1" in
 		echo "This could take several minutes, or longer if your machine is slow"
 		echo "or there is a large update to install."
 		echo "Output will be logged to ${LOG_PATH}"
-#		test -f ${INSTALL_PATH} || exit_not_installed
+		# test -f ${INSTALL_PATH} || exit_not_installed
 
 		echo "Attempting to download http://duckpan.com/install.pl as duckpan-install.pl"
 		su -l vagrant -c 'wget -L http://duckpan.com/install.pl -O duckpan-install.pl' || exit_failed_to_download
@@ -54,13 +57,15 @@ case "$1" in
 		su -l vagrant -c 'bash -l -i -c "perl duckpan-install.pl"' || exit_failed_to_run
 		echo "DuckPAN was updated successfully or there was no update to install."
 
-		# /etc/init/lightdm.override makes LightDM wait for this signal for 2 reasons:
+		# /etc/init/lightdm.override makes LightDM wait for this signal for
+		# 2 reasons:
 		# 1. The user really shouldn't start using the VM until DuckPAN has been
 		#    updated.
-		# 2. There seems to be a bug whereby boot logging (to /var/log/boot.log) does
-		#    not occur while LightDM/X.org is starting. This only happens when the
-		#    VirtualBox Guest Additions are in use. It usually interferes with this
-		#    init script's logging, as well as other init scripts too.
+		# 2. There seems to be a bug whereby boot logging (to /var/log/boot.log)
+		#    does not occur while LightDM/X.org is starting. This only happens
+		#    when the VirtualBox Guest Additions are in use. It usually
+		#    interferes with this init script's logging, as well as other
+		#    init scripts too.
 		initctl emit --no-wait duckpan-updated
 		;;
 	stop)
